// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxkgdwgomycnaohirtkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4a2dkd2dvbXljbmFvaGlydGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MzQ3NTIsImV4cCI6MjA1MzQxMDc1Mn0.2IQXDJlye2B3H03Uojl13DSIaGndkwExPdpmwlQsHMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);